"""
Report Exporter Service

Exports productivity reports in various formats (Markdown, JSON, CSV).
"""

from datetime import datetime, timedelta
from typing import Dict, List
import json
import csv
from io import StringIO


class ReportExporter:
    """Exports productivity reports in multiple formats."""
    
    def __init__(self, db_connection):
        """Initialize exporter."""
        self.db = db_connection
    
    def export_weekly_report(self, format: str = 'markdown', week_offset: int = 0) -> str:
        """
        Export weekly report.
        
        Args:
            format: 'markdown', 'json', or 'csv'
            week_offset: Weeks back (0 = this week)
        
        Returns:
            Report content as string
        """
        from backend.services.llm_weekly_review import get_llm_weekly_review
        from backend.services.productivity_patterns import get_productivity_pattern_analyzer
        from backend.services.heatmap_generator import get_heatmap_generator
        
        review_service = get_llm_weekly_review(self.db)
        analyzer = get_productivity_pattern_analyzer(self.db)
        heatmap_gen = get_heatmap_generator(self.db)
        
        # Get review data
        review = review_service.generate_weekly_review(week_offset)
        
        if format == 'markdown':
            return self._export_markdown(review, heatmap_gen)
        elif format == 'json':
            return self._export_json(review)
        elif format == 'csv':
            return self._export_csv(review)
        else:
            raise ValueError(f"Unsupported format: {format}")
    
    def _export_markdown(self, review: Dict, heatmap_gen) -> str:
        """Export as Markdown."""
        md = []
        
        # Header
        md.append(f"# 📊 Weekly Productivity Report")
        md.append(f"**{review['week_start']} to {review['week_end']}**")
        md.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")
        md.append("---\n")
        
        # LLM Review
        md.append("## 🤖 AI Review\n")
        md.append(review['review_text'])
        md.append("\n---\n")
        
        # Heatmap
        md.append("## 🔥 Productivity Heatmap\n")
        md.append("```")
        try:
            heatmap = heatmap_gen.generate_weekly_heatmap()
            md.append(heatmap)
        except:
            md.append("Heatmap unavailable")
        md.append("```\n")
        
        # Raw Data
        data = review['raw_data']
        md.append("## 📈 Statistics\n")
        md.append(f"- **Total Time:** {data['total_hours']}h ({data['change_vs_last_week']} vs last week)")
        md.append(f"- **Focus Score:** {data['avg_focus']}/100")
        md.append(f"- **Goal Alignment:** {data['goal_alignment_pct']}%")
        md.append(f"- **Distractions:** {data['distraction_time']}")
        md.append(f"- **Context Switches:** {data['context_switches']}")
        md.append(f"- **Peak Hour:** {data['peak_hours']}\n")
        
        # Sessions
        md.append("## 💼 Sessions\n")
        md.append(f"- Total: {data['total_sessions']}")
        md.append(f"- Coding: {data['coding_sessions']}")
        md.append(f"- Research: {data['research_sessions']}")
        md.append(f"- Avg Length: {data['avg_session_length']}min\n")
        
        # Best/Worst Days
        md.append("## 📅 Daily Breakdown\n")
        md.append(f"- **Best Day:** {data['best_day']} ({data['best_day_score']}/100)")
        md.append(f"- **Challenging Day:** {data['worst_day']} ({data['worst_day_score']}/100)\n")
        
        # Habits
        md.append("## 🎯 Habits\n")
        md.append(data['habits_status'])
        md.append("\n")
        
        # Footer
        md.append("---")
        md.append("\n*Generated by KrypticTrack - Your Laptop Brain 🧠*")
        
        return "\n".join(md)
    
    def _export_json(self, review: Dict) -> str:
        """Export as JSON."""
        return json.dumps(review, indent=2)
    
    def _export_csv(self, review: Dict) -> str:
        """Export raw data as CSV."""
        output = StringIO()
        writer = csv.writer(output)
        
        # Headers
        writer.writerow(['Metric', 'Value'])
        
        # Data
        data = review['raw_data']
        for key, value in data.items():
            writer.writerow([key, value])
        
        return output.getvalue()
    
    def save_report(self, content: str, filename: str):
        """Save report to file."""
        from pathlib import Path
        
        reports_dir = Path('reports')
        reports_dir.mkdir(exist_ok=True)
        
        filepath = reports_dir / filename
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        return str(filepath)


def get_report_exporter(db_connection):
    """Get report exporter instance."""
    return ReportExporter(db_connection)
